---
title: "Grid search optimization results"
output: pdf_document
header-includes: \usepackage{setspace}
---
\doublespacing 

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# Grid search

The COBYLA algorithm, which we use for optimization of transition rate parameters $(\log(k_{0ij}), k_{1ij})$, is a local solver. This means that for any given set of initial values, the returned solution may only be locally optimal. In an effort to find the global optimum, we perform a grid search over different sets of initial values for $(\log(k_{0ij}), k_{1ij})$. The grid of values is comprised of pairwise combinations of equally spaced values $\log(k_{0ij}) = (-12, -10, -8, -6)$ and $k_{1ij} = (0.02, 0.04\overline{6}, 0.07\overline{3}, 0.10)$, for 16 possible sets of initial values. A given pair $(\log(k_0), k_1)$ is used as a set of initial values for all 12 transitions (24 parameters) in the optimization, i.e. the initial values for transitions $r_{12}, r_{16}, \dots, r_{94}$ are all the same for some pair $(\log(k_0), k_1)$ from the grid.

Some pairs of initial values are _invalid_, meaning at least one of the constraints on the parameter space is violated at the initial values and the algorithm will not start. Additionally, for two sets of initial values that are _initially_ valid, the algorithm ventures outside the constraint space within the first few iterations and does not return. We also call these initial values invalid, and we ignore all invalid pairs of initial values. There are 8 valid pairs of initial values, which we let run to convergence.

We define convergence using a relative tolerance of 0.005 for all parameters, where the relative tolerance between two values $x$ and $y$ is defined as 
\begin{align}
reltol(x, y) & = \vert x - y \vert / \mbox{min}(\vert x \vert, \vert y \vert).
\end{align}
For the algorithm to converge on iteration $m$, all 24 parameters $k$ must have $reltol(k^{(m)}, k^{(m - 1)}) < 0.005$.

# Results

## Optimal parameters

